[theme]

# Primary accent for interactive elements
primaryColor = '#FF2768'

# Background color for the main content area
backgroundColor = '#F7F5F6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#68B6EF'

# Color used for almost all text
textColor = '#1D1C1A'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = 'serif'
