[theme]

# Primary accent for interactive elements
primaryColor = '#A398F0'

# Background color for the main content area
backgroundColor = '#F6F9FE'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F2E4FB'

# Color used for almost all text
textColor = '#061328'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = 'sans serif'

